stages:
  - validate
  - release
  - renovate_bot

variables:
  SHELLCHECK_ARGS: --source-path=. --source-path=./lib/ --external-sources

include:
  - local: .gitlab-ci-asdf-versions.yml

  # This template should be included in all Infrastructure projects.
  # It includes standard checks, gitlab-scanners, validations and release processes
  # common to all projects using this template library.
  # see https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks/-/blob/main/README.md#templatesstandardyml
  - project: 'gitlab-com/gl-infra/common-ci-tasks'
    ref: v1.24.0 # renovate:managed
    file: templates/standard.yml

test:
  stage: validate
  image:
    name: registry.gitlab.com/gitlab-com/gl-infra/common-ci-tasks/renovate:v1.23.1
    entrypoint: [""]
  needs: []
  script: |
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf
    source ~/.asdf/asdf.sh
    asdf plugin test asdf-promtool "${CI_REPOSITORY_URL}" --asdf-plugin-gitref "${CI_COMMIT_BRANCH}" promtool
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
