stages:
  - validate
  - release
  - renovate_bot

variables:
  SHELLCHECK_ARGS: --source-path=. --source-path=./lib/ --external-sources

include:
  - local: .gitlab-ci-asdf-versions.yml

  # This template should be included in all Infrastructure projects.
  # It includes standard checks, gitlab-scanners, validations and release processes
  # common to all projects using this template library.
  # see https://gitlab.com/gitlab-com/gl-infra/common-ci-tasks/-/blob/main/README.md#templatesstandardyml
  - project: "gitlab-com/gl-infra/common-ci-tasks"
    ref: v1.35.0 # renovate:managed
    file: templates/standard.yml

test:
  stage: validate
  image:
    name: registry.gitlab.com/gitlab-com/gl-infra/common-ci-tasks/renovate:v1.35.0
    entrypoint: [""]
  needs: []
  script:
    - apt-get update && apt-get install -y jq curl git
    - git clone https://github.com/asdf-vm/asdf.git ~/.asdf
    - source ~/.asdf/asdf.sh
    - echo "Running test suite with 'asdf plugin test ${OVERRIDE_TOOLNAME} ${CI_REPOSITORY_URL} --asdf-plugin-gitref ${CI_COMMIT_SHA} ${OVERRIDE_TOOLNAME}'"
    - asdf plugin test "${OVERRIDE_TOOLNAME}" "${CI_REPOSITORY_URL}" --asdf-plugin-gitref "${CI_COMMIT_SHA}" "${OVERRIDE_TOOLNAME}" --version
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  parallel:
    matrix:
      - OVERRIDE_TOOLNAME: ["promtool", "amtool", "thanos"]
