# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-json
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
  - repo: local
    hooks:
    -   id: shellcheck
        name: shellcheck
        entry: shellcheck -P . -P ./test/ -P ./test/lib/ -P ./test/integration/ -x
        language: system
        files: '^(.*\.sh|bin/[^\.]*)$'
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.4.3-1 # Note: keep this in sync with .tool-versions
    hooks:
      - id: shfmt
        args: [-w, -s, -i, "2"]
